<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('students')->insert([
            [
                'Student_ID' => 1,
                'LRN' => '123456789012',
                'Grade_Level' => '7',
                'FirstName' => 'Alice',
                'LastName' => 'Smith',
                'MiddleName' => 'Marie',
                'Suffix' => 'Jr.',
                'BirthDate' => '2010-05-10',
                'Sex' => 'F',
                'Age' => 15,
                'Religion' => 'Christian',
                'HouseNo' => '123',
                'Barangay' => 'Barangay 1',
                'Municipality' => 'City A',
                'Province' => 'Province A',
                'MotherName' => 'Jane Smith',
                'FatherName' => 'John Smith',
                'Guardian' => 'Jane Smith',
                'Relationship' => 'Mother',
                'ContactNumber' => '09171234567',
                'Curriculum' => 'JHS',
                'Track' => 'Academic',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 2,
                'LRN' => '987654321098',
                'Grade_Level' => '7',
                'FirstName' => 'Bob',
                'LastName' => 'Johnson',
                'MiddleName' => 'Edward',
                'Suffix' => 'Sr.',
                'BirthDate' => '2010-08-15',
                'Sex' => 'M',
                'Age' => 15,
                'Religion' => 'Christian',
                'HouseNo' => '456',
                'Barangay' => 'Barangay 2',
                'Municipality' => 'City B',
                'Province' => 'Province B',
                'MotherName' => 'Anna Johnson',
                'FatherName' => 'Robert Johnson',
                'Guardian' => 'Anna Johnson',
                'Relationship' => 'Mother',
                'ContactNumber' => '09179876543',
                'Curriculum' => 'SHS',
                'Track' => 'Technical-Vocational',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 3,
                'LRN' => '111122223333',
                'Grade_Level' => '7',
                'FirstName' => 'Carol',
                'LastName' => 'Baker',
                'MiddleName' => 'Ann',
                'Suffix' => null,
                'BirthDate' => '2009-11-20',
                'Sex' => 'F',
                'Age' => 16,
                'Religion' => 'Catholic',
                'HouseNo' => '789',
                'Barangay' => 'Barangay 3',
                'Municipality' => 'City C',
                'Province' => 'Province C',
                'MotherName' => 'Maria Baker',
                'FatherName' => 'Daniel Baker',
                'Guardian' => 'Maria Baker',
                'Relationship' => 'Mother',
                'ContactNumber' => '09178881234',
                'Curriculum' => 'SHS',
                'Track' => 'Academic',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 4,
                'LRN' => '444455556666',
                'Grade_Level' => '7',
                'FirstName' => 'David',
                'LastName' => 'Cruz',
                'MiddleName' => 'Lee',
                'Suffix' => null,
                'BirthDate' => '2008-02-18',
                'Sex' => 'M',
                'Age' => 17,
                'Religion' => 'Muslim',
                'HouseNo' => '101',
                'Barangay' => 'Barangay 4',
                'Municipality' => 'City D',
                'Province' => 'Province D',
                'MotherName' => 'Lea Cruz',
                'FatherName' => 'Martin Cruz',
                'Guardian' => 'Martin Cruz',
                'Relationship' => 'Father',
                'ContactNumber' => '09174561234',
                'Curriculum' => 'SHS',
                'Track' => 'Arts and Design',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 5,
                'LRN' => '777788889999',
                'Grade_Level' => '7',
                'FirstName' => 'Eve',
                'LastName' => 'Lopez',
                'MiddleName' => 'Grace',
                'Suffix' => null,
                'BirthDate' => '2010-12-01',
                'Sex' => 'F',
                'Age' => 14,
                'Religion' => 'Christian',
                'HouseNo' => '202',
                'Barangay' => 'Barangay 5',
                'Municipality' => 'City E',
                'Province' => 'Province E',
                'MotherName' => 'Carmen Lopez',
                'FatherName' => 'Jose Lopez',
                'Guardian' => 'Carmen Lopez',
                'Relationship' => 'Mother',
                'ContactNumber' => '09173456789',
                'Curriculum' => 'JHS',
                'Track' => 'Sports',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 6,
                'LRN' => '999900001111',
                'Grade_Level' => '7',
                'FirstName' => 'Frank',
                'LastName' => 'Garcia',
                'MiddleName' => 'James',
                'Suffix' => null,
                'BirthDate' => '2009-04-25',
                'Sex' => 'M',
                'Age' => 16,
                'Religion' => 'Catholic',
                'HouseNo' => '303',
                'Barangay' => 'Barangay 6',
                'Municipality' => 'City F',
                'Province' => 'Province F',
                'MotherName' => 'Isabel Garcia',
                'FatherName' => 'Carlos Garcia',
                'Guardian' => 'Carlos Garcia',
                'Relationship' => 'Father',
                'ContactNumber' => '09172345678',
                'Curriculum' => 'SHS',
                'Track' => 'TVL',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 7,
                'LRN' => '222233334444',
                'Grade_Level' => '8',
                'FirstName' => 'Grace',
                'LastName' => 'Nguyen',
                'MiddleName' => 'Kim',
                'Suffix' => null,
                'BirthDate' => '2010-01-10',
                'Sex' => 'F',
                'Age' => 15,
                'Religion' => 'Buddhist',
                'HouseNo' => '404',
                'Barangay' => 'Barangay 7',
                'Municipality' => 'City G',
                'Province' => 'Province G',
                'MotherName' => 'Lan Nguyen',
                'FatherName' => 'Tuan Nguyen',
                'Guardian' => 'Lan Nguyen',
                'Relationship' => 'Mother',
                'ContactNumber' => '09172223333',
                'Curriculum' => 'JHS',
                'Track' => 'Academic',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 8,
                'LRN' => '555566667777',
                'Grade_Level' => '8',
                'FirstName' => 'Henry',
                'LastName' => 'Reyes',
                'MiddleName' => 'Joel',
                'Suffix' => null,
                'BirthDate' => '2011-06-22',
                'Sex' => 'M',
                'Age' => 14,
                'Religion' => 'Christian',
                'HouseNo' => '505',
                'Barangay' => 'Barangay 8',
                'Municipality' => 'City H',
                'Province' => 'Province H',
                'MotherName' => 'Elena Reyes',
                'FatherName' => 'Victor Reyes',
                'Guardian' => 'Victor Reyes',
                'Relationship' => 'Father',
                'ContactNumber' => '09171112222',
                'Curriculum' => 'JHS',
                'Track' => 'TVL',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 9,
                'LRN' => '666677778888',
                'Grade_Level' => '8',
                'FirstName' => 'Isla',
                'LastName' => 'Torres',
                'MiddleName' => 'Faith',
                'Suffix' => null,
                'BirthDate' => '2008-09-09',
                'Sex' => 'F',
                'Age' => 17,
                'Religion' => 'Christian',
                'HouseNo' => '606',
                'Barangay' => 'Barangay 9',
                'Municipality' => 'City I',
                'Province' => 'Province I',
                'MotherName' => 'Rebecca Torres',
                'FatherName' => 'Jorge Torres',
                'Guardian' => 'Rebecca Torres',
                'Relationship' => 'Mother',
                'ContactNumber' => '09179998888',
                'Curriculum' => 'SHS',
                'Track' => 'Arts and Design',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 10,
                'LRN' => '333344445555',
                'Grade_Level' => '11',
                'FirstName' => 'Jake',
                'LastName' => 'Santos',
                'MiddleName' => 'Paul',
                'Suffix' => null,
                'BirthDate' => '2009-03-30',
                'Sex' => 'M',
                'Age' => 16,
                'Religion' => 'Christian',
                'HouseNo' => '707',
                'Barangay' => 'Barangay 10',
                'Municipality' => 'City J',
                'Province' => 'Province J',
                'MotherName' => 'Lucia Santos',
                'FatherName' => 'Marco Santos',
                'Guardian' => 'Lucia Santos',
                'Relationship' => 'Mother',
                'ContactNumber' => '09175556666',
                'Curriculum' => 'SHS',
                'Track' => 'Academic',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 11,
                'LRN' => '121212121212',
                'Grade_Level' => '11',
                'FirstName' => 'Karen',
                'LastName' => 'Villanueva',
                'MiddleName' => 'Hope',
                'Suffix' => null,
                'BirthDate' => '2010-07-07',
                'Sex' => 'F',
                'Age' => 15,
                'Religion' => 'Catholic',
                'HouseNo' => '808',
                'Barangay' => 'Barangay 11',
                'Municipality' => 'City K',
                'Province' => 'Province K',
                'MotherName' => 'Eva Villanueva',
                'FatherName' => 'Leo Villanueva',
                'Guardian' => 'Eva Villanueva',
                'Relationship' => 'Mother',
                'ContactNumber' => '09174443333',
                'Curriculum' => 'JHS',
                'Track' => 'Sports',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 12,
                'LRN' => '343434343434',
                'Grade_Level' => '11',
                'FirstName' => 'Liam',
                'LastName' => 'Del Rosario',
                'MiddleName' => 'Jay',
                'Suffix' => null,
                'BirthDate' => '2011-10-05',
                'Sex' => 'M',
                'Age' => 14,
                'Religion' => 'Christian',
                'HouseNo' => '909',
                'Barangay' => 'Barangay 12',
                'Municipality' => 'City L',
                'Province' => 'Province L',
                'MotherName' => 'Gina Del Rosario',
                'FatherName' => 'Ben Del Rosario',
                'Guardian' => 'Gina Del Rosario',
                'Relationship' => 'Mother',
                'ContactNumber' => '09172224444',
                'Curriculum' => 'JHS',
                'Track' => 'Academic',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 13,
                'LRN' => '454545454545',
                'Grade_Level' => '12',
                'FirstName' => 'Mia',
                'LastName' => 'Fernandez',
                'MiddleName' => 'Rose',
                'Suffix' => null,
                'BirthDate' => '2007-03-15',
                'Sex' => 'F',
                'Age' => 18,
                'Religion' => 'Catholic',
                'HouseNo' => '1010',
                'Barangay' => 'Barangay 13',
                'Municipality' => 'City M',
                'Province' => 'Province M',
                'MotherName' => 'Maria Fernandez',
                'FatherName' => 'Jose Fernandez',
                'Guardian' => 'Maria Fernandez',
                'Relationship' => 'Mother',
                'ContactNumber' => '09173335555',
                'Curriculum' => 'SHS',
                'Track' => 'STEM',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 14,
                'LRN' => '565656565656',
                'Grade_Level' => '12',
                'FirstName' => 'Noah',
                'LastName' => 'Lim',
                'MiddleName' => 'Kai',
                'Suffix' => null,
                'BirthDate' => '2007-06-20',
                'Sex' => 'M',
                'Age' => 18,
                'Religion' => 'Buddhist',
                'HouseNo' => '1111',
                'Barangay' => 'Barangay 14',
                'Municipality' => 'City N',
                'Province' => 'Province N',
                'MotherName' => 'Mei Lim',
                'FatherName' => 'Wei Lim',
                'Guardian' => 'Mei Lim',
                'Relationship' => 'Mother',
                'ContactNumber' => '09174446666',
                'Curriculum' => 'SHS',
                'Track' => 'ABM',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ],
            [
                'Student_ID' => 15,
                'LRN' => '676767676767',
                'Grade_Level' => '12',
                'FirstName' => 'Olivia',
                'LastName' => 'Ramos',
                'MiddleName' => 'Grace',
                'Suffix' => null,
                'BirthDate' => '2007-09-25',
                'Sex' => 'F',
                'Age' => 18,
                'Religion' => 'Christian',
                'HouseNo' => '1212',
                'Barangay' => 'Barangay 15',
                'Municipality' => 'City O',
                'Province' => 'Province O',
                'MotherName' => 'Sofia Ramos',
                'FatherName' => 'Miguel Ramos',
                'Guardian' => 'Sofia Ramos',
                'Relationship' => 'Mother',
                'ContactNumber' => '09175557777',
                'Curriculum' => 'SHS',
                'Track' => 'HUMSS',
                'created_at' => now(),
                'updated_at' => now(),
                'Status' => 'Accepted',
            ]
        ]);
    }
}