<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StudentModel;

class StudentTableSeeder extends Seeder
{
    public function run(): void
    {
        $students = [
            [
                'Student_ID' => 1,
                'LRN' => '123456789012',
                'Grade_Level' => '11',
                'FirstName' => 'John',
                'LastName' => 'Doe',
                'MiddleName' => 'Smith',
                'Suffix' => 'Jr.',
                'BirthDate' => '2005-05-15',
                'Sex' => 'M',
                'Age' => '18',
                'Religion' => 'Catholic',
                'HouseNo' => '123',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Jane Doe',
                'FatherName' => 'John Doe Sr',
                'Guardian' => 'Jane Doe',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456789',
                'Curriculum' => 'SHS',
                'Track' => 'STEM',
                'Status' => 'Accepted',
                'comments' => 'Updated via seeder'
            ],
            [
                'Student_ID' => 2,
                'LRN' => '123456789013',
                'Grade_Level' => '11',
                'FirstName' => 'Maria',
                'LastName' => 'Santos',
                'MiddleName' => 'Garcia',
                'Suffix' => null,
                'BirthDate' => '2005-06-20',
                'Sex' => 'F',
                'Age' => '18',
                'Religion' => 'Catholic',
                'HouseNo' => '456',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Ana Santos',
                'FatherName' => 'Pedro Santos',
                'Guardian' => 'Ana Santos',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456790',
                'Curriculum' => 'SHS',
                'Track' => 'STEM',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 3,
                'LRN' => '123456789014',
                'Grade_Level' => '11',
                'FirstName' => 'James',
                'LastName' => 'Wilson',
                'MiddleName' => 'Brown',
                'Suffix' => null,
                'BirthDate' => '2005-07-10',
                'Sex' => 'M',
                'Age' => '18',
                'Religion' => 'Protestant',
                'HouseNo' => '789',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Sarah Wilson',
                'FatherName' => 'Michael Wilson',
                'Guardian' => 'Sarah Wilson',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456791',
                'Curriculum' => 'SHS',
                'Track' => 'ABM',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 4,
                'LRN' => '123456789015',
                'Grade_Level' => '11',
                'FirstName' => 'Sophia',
                'LastName' => 'Lee',
                'MiddleName' => 'Chen',
                'Suffix' => null,
                'BirthDate' => '2005-08-25',
                'Sex' => 'F',
                'Age' => '18',
                'Religion' => 'Buddhist',
                'HouseNo' => '101',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Mei Lee',
                'FatherName' => 'Wei Lee',
                'Guardian' => 'Mei Lee',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456792',
                'Curriculum' => 'SHS',
                'Track' => 'HUMSS',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 5,
                'LRN' => '123456789016',
                'Grade_Level' => '11',
                'FirstName' => 'Lucas',
                'LastName' => 'Martinez',
                'MiddleName' => 'Rodriguez',
                'Suffix' => null,
                'BirthDate' => '2005-09-15',
                'Sex' => 'M',
                'Age' => '18',
                'Religion' => 'Catholic',
                'HouseNo' => '202',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Isabella Martinez',
                'FatherName' => 'Carlos Martinez',
                'Guardian' => 'Isabella Martinez',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456793',
                'Curriculum' => 'SHS',
                'Track' => 'GAS',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 6,
                'LRN' => '123456789017',
                'Grade_Level' => '11',
                'FirstName' => 'Emma',
                'LastName' => 'Kim',
                'MiddleName' => 'Park',
                'Suffix' => null,
                'BirthDate' => '2005-10-05',
                'Sex' => 'F',
                'Age' => '18',
                'Religion' => 'Christian',
                'HouseNo' => '303',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Soo Kim',
                'FatherName' => 'Jin Kim',
                'Guardian' => 'Soo Kim',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456794',
                'Curriculum' => 'SHS',
                'Track' => 'STEM',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 7,
                'LRN' => '123456789018',
                'Grade_Level' => '11',
                'FirstName' => 'Noah',
                'LastName' => 'Garcia',
                'MiddleName' => 'Lopez',
                'Suffix' => null,
                'BirthDate' => '2005-11-20',
                'Sex' => 'M',
                'Age' => '18',
                'Religion' => 'Catholic',
                'HouseNo' => '404',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Maria Garcia',
                'FatherName' => 'Juan Garcia',
                'Guardian' => 'Maria Garcia',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456795',
                'Curriculum' => 'SHS',
                'Track' => 'ABM',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 8,
                'LRN' => '123456789019',
                'Grade_Level' => '11',
                'FirstName' => 'Olivia',
                'LastName' => 'Nguyen',
                'MiddleName' => 'Tran',
                'Suffix' => null,
                'BirthDate' => '2005-12-10',
                'Sex' => 'F',
                'Age' => '18',
                'Religion' => 'Buddhist',
                'HouseNo' => '505',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Mai Nguyen',
                'FatherName' => 'Hai Nguyen',
                'Guardian' => 'Mai Nguyen',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456796',
                'Curriculum' => 'SHS',
                'Track' => 'HUMSS',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 9,
                'LRN' => '123456789020',
                'Grade_Level' => '11',
                'FirstName' => 'Ethan',
                'LastName' => 'Patel',
                'MiddleName' => 'Sharma',
                'Suffix' => null,
                'BirthDate' => '2006-01-15',
                'Sex' => 'M',
                'Age' => '17',
                'Religion' => 'Hindu',
                'HouseNo' => '606',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Priya Patel',
                'FatherName' => 'Raj Patel',
                'Guardian' => 'Priya Patel',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456797',
                'Curriculum' => 'SHS',
                'Track' => 'STEM',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 10,
                'LRN' => '123456789021',
                'Grade_Level' => '11',
                'FirstName' => 'Ava',
                'LastName' => 'Anderson',
                'MiddleName' => 'Taylor',
                'Suffix' => null,
                'BirthDate' => '2006-02-20',
                'Sex' => 'F',
                'Age' => '17',
                'Religion' => 'Protestant',
                'HouseNo' => '707',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Emily Anderson',
                'FatherName' => 'David Anderson',
                'Guardian' => 'Emily Anderson',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456798',
                'Curriculum' => 'SHS',
                'Track' => 'GAS',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 11,
                'LRN' => '123456789022',
                'Grade_Level' => '11',
                'FirstName' => 'William',
                'LastName' => 'Thompson',
                'MiddleName' => 'Clark',
                'Suffix' => null,
                'BirthDate' => '2006-03-25',
                'Sex' => 'M',
                'Age' => '17',
                'Religion' => 'Christian',
                'HouseNo' => '808',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Sarah Thompson',
                'FatherName' => 'Robert Thompson',
                'Guardian' => 'Sarah Thompson',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456799',
                'Curriculum' => 'SHS',
                'Track' => 'ABM',
                'Status' => 'Accepted',
                'comments' => null
            ],
            [
                'Student_ID' => 12,
                'LRN' => '123456789023',
                'Grade_Level' => '11',
                'FirstName' => 'Isabella',
                'LastName' => 'White',
                'MiddleName' => 'Johnson',
                'Suffix' => null,
                'BirthDate' => '2006-04-30',
                'Sex' => 'F',
                'Age' => '17',
                'Religion' => 'Catholic',
                'HouseNo' => '909',
                'Barangay' => 'Sample Barangay',
                'Municipality' => 'Sample Municipality',
                'Province' => 'Sample Province',
                'MotherName' => 'Mary White',
                'FatherName' => 'John White',
                'Guardian' => 'Mary White',
                'Relationship' => 'Mother',
                'ContactNumber' => '09123456800',
                'Curriculum' => 'SHS',
                'Track' => 'HUMSS',
                'Status' => 'Accepted',
                'comments' => null
            ]
        ];

        foreach ($students as $student) {
            StudentModel::updateOrCreate(
                ['Student_ID' => $student['Student_ID']],
                $student
            );
        }
    }
}